export default [
  { id: 1, name: "Perro Mini", price: 3500, category: "Perros calientes" },
  { id: 2, name: "Perro Sencillo", price: 9000, category: "Perros calientes" },
  { id: 3, name: "Perro Doble Salchicha", price: 13000, category: "Perros calientes" },
  { id: 4, name: "Choriperro", price: 14000, category: "Perros calientes" },
  { id: 5, name: "Butiperro", price: 0, category: "Perros calientes" },
  { id: 6, name: "Ranchero", price: 0, category: "Perros calientes" },
  { id: 7, name: "Perra Sencilla", price: 12000, category: "Perros calientes" },
  { id: 8, name: "Medio Suizo", price: 12000, category: "Perros calientes" },
  { id: 9, name: "Suizo", price: 15000, category: "Perros calientes" },
  { id: 10, name: "Super Perro Sencillo", price: 0, category: "Perros calientes" },
  { id: 11, name: "La Perrada de Piter", price: 24000, category: "Perros calientes" },

  { id: 12, name: "Hamburguesa Mini", price: 6000, category: "Hamburguesas" },
  { id: 13, name: "Hamburguesa Sencilla", price: 12000, category: "Hamburguesas" },
  { id: 14, name: "Hamburguesa Doble Carne", price: 17000, category: "Hamburguesas" },
  { id: 15, name: "Hamburguesa La Perrada de Piter", price: 22000, category: "Hamburguesas" },

  { id: 16, name: "Mini Suizo al Vapor", price: 11000, category: "Suizos" },
  { id: 17, name: "Mini Suizo a la Francesa", price: 13000, category: "Suizos" },
  { id: 18, name: "Suizo al Vapor", price: 17000, category: "Suizos" },
  { id: 19, name: "Suizo a la Francesa", price: 19000, category: "Suizos" },
  { id: 20, name: "Suizo La Perrada de Piter", price: 25000, category: "Suizos" },

  { id: 21, name: "Salchipapa Mini", price: 9000, category: "Salchipapa" },
  { id: 22, name: "Salchipapa Sencilla", price: 14000, category: "Salchipapa" },
  { id: 23, name: "Salchipapa Mixta", price: 0, category: "Salchipapa" },
  { id: 24, name: "Salchipapa Especial", price: 21000, category: "Salchipapa" },
  { id: 25, name: "Salchipapa Doble", price: 25000, category: "Salchipapa" },
  { id: 26, name: "Salchipapa La Perrada de Piter", price: 35000, category: "Salchipapa" },

  { id: 27, name: "Picada Sencilla al Vapor", price: 17000, category: "Picadas" },
  { id: 28, name: "Picada Sencilla a la Francesa", price: 19000, category: "Picadas" },
  { id: 29, name: "Picada Res al Vapor", price: 18000, category: "Picadas" },
  { id: 30, name: "Picada Res a la Francesa", price: 20000, category: "Picadas" },
  { id: 31, name: "Picada Pollo al Vapor", price: 18000, category: "Picadas" },
  { id: 32, name: "Picada Pollo a la Francesa", price: 20000, category: "Picadas" },
  { id: 33, name: "Picada Res y Pollo", price: 25000, category: "Picadas" },
  { id: 34, name: "Picada para 2 Personas", price: 30000, category: "Picadas" },
  { id: 35, name: "Picada para 3 Personas", price: 45000, category: "Picadas" },
  { id: 36, name: "Picada para 4 Personas", price: 60000, category: "Picadas" },

  { id: 37, name: "Arepa de Queso", price: 4000, category: "Arepas sencillas" },
  { id: 38, name: "Arepa de Jamón", price: 4000, category: "Arepas sencillas" },
  { id: 39, name: "Arepa de Jamón y Queso", price: 5000, category: "Arepas sencillas" },
  { id: 40, name: "Arepa de Butifarra", price: 6000, category: "Arepas sencillas" },

  { id: 41, name: "Arepa de Pollo Desmechado", price: 2500, category: "Arepas típicas" },
  { id: 42, name: "Arepa de Carne Desmechada", price: 2500, category: "Arepas típicas" },
  { id: 43, name: "Arepa de Carne de Hamburguesa", price: 3500, category: "Arepas típicas" },
  { id: 44, name: "Arepa Suiza", price: 3000, category: "Arepas típicas" },
  { id: 45, name: "Arepa de Chorizo", price: 5000, category: "Arepas típicas" },
  { id: 46, name: "Arepa Ranchera", price: 9000, category: "Arepas típicas" },

  { id: 47, name: "Arepa de Pollo y Carne y Suiza", price: 0, category: "Arepas trifásicas" },
  { id: 48, name: "Arepa de Carne de Hamburguesa y Chorizo y Butifarra", price: 0, category: "Arepas trifásicas" },

  { id: 49, name: "Arepa de Pollo y Carne Desmechada", price: 0, category: "Arepas dobles" },
  { id: 50, name: "Arepa de Pollo y Carne de Hamburguesa", price: 0, category: "Arepas dobles" },
  { id: 51, name: "Arepa de Pollo y Suiza", price: 0, category: "Arepas dobles" },
  { id: 52, name: "Arepa de Pollo y Chorizo", price: 0, category: "Arepas dobles" },
  { id: 53, name: "Arepa de Pollo y Ranchera", price: 0, category: "Arepas dobles" },
  { id: 54, name: "Arepa de Pollo y Butifarra", price: 0, category: "Arepas dobles" },

  { id: 55, name: "Arepa de Carne y Carne de Hamburguesa", price: 0, category: "Arepas dobles" },
  { id: 56, name: "Arepa de Carne y Suiza", price: 0, category: "Arepas dobles" },
  { id: 57, name: "Arepa de Carne y Chorizo", price: 0, category: "Arepas dobles" },
  { id: 58, name: "Arepa de Carne y Ranchera", price: 0, category: "Arepas dobles" },
  { id: 59, name: "Arepa de Carne y Butifarra", price: 0, category: "Arepas dobles" },
  { id: 60, name: "Arepa Suiza y Butifarra", price: 0, category: "Arepas dobles" },
  { id: 61, name: "Arepa Suiza y Chorizo", price: 0, category: "Arepas dobles" },
  { id: 62, name: "Arepa Suiza y Ranchera", price: 0, category: "Arepas dobles" },
  { id: 63, name: "Arepa Suiza y Carne de Hamburguesa", price: 0, category: "Arepas dobles" },

  { id: 64, name: "Arepa de Chorizo y Butifarra", price: 0, category: "Arepas dobles" },
  { id: 65, name: "Arepa de Chorizo y Ranchera", price: 0, category: "Arepas dobles" },
  { id: 66, name: "Arepa de Chorizo y Carne de Hamburguesa", price: 0, category: "Arepas dobles" },

  { id: 67, name: "Gaseosa Personal", price: 2500, category: "Bebidas" },
  { id: 68, name: "Agua", price: 2500, category: "Bebidas" },
  { id: 69, name: "Agua Saborizada", price: 3000, category: "Bebidas" },
  { id: 70, name: "Jugo del Valle", price: 3000, category: "Bebidas" },
  { id: 71, name: "Gaseosa Plástica 400ml", price: 4000, category: "Bebidas" },
  { id: 72, name: "Gaseosa 1L", price: 5000, category: "Bebidas" },
  { id: 73, name: "Gaseosa 1.5L", price: 9000, category: "Bebidas" },
  { id: 74, name: "Gaseosa 2.5L", price: 13000, category: "Bebidas" },

  { id: 75, name: "Queso Gratinado", price: 5000, category: "Adiciones" },
  { id: 76, name: "Butifarra", price: 3500, category: "Adiciones" },
  { id: 77, name: "Papa Francesa", price: 5000, category: "Adiciones" }
];
